config/routes.rb
Raghava::Application.routes.draw do
  devise_for :users
  resources :products

  resources :logins

  get "home/ContactUs"

  authenticated :user do
  root :to => "products#index"
end
unauthenticated :user do
  devise_scope :user do 
    get "/" => "devise/sessions#new"
  end
end

end

app/models/login.rb
class Login < ActiveRecord::Base
	#has_many :products ,presence => true
end

app/models/product.rb
class Product < ActiveRecord::Base
	#belongs_to :Login , foreign_key :Login_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
  	root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout "brain", :only => :OverView
  def AboutUs
  end
	
  def OverView
  	 
  end

  def ContactUs
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :set_login, only: [:show, :edit, :update, :destroy]

  # GET /logins
  # GET /logins.json
  def index
    @logins = Login.all
  end

  # GET /logins/1
  # GET /logins/1.json
  def show
  end

  # GET /logins/new
  def new
    @login = Login.new
  end

  # GET /logins/1/edit
  def edit
  end

  # POST /logins
  # POST /logins.json
  def create
    @login = Login.new(login_params)

    respond_to do |format|
      if @login.save
        UserMailer.registration_confirmation(@login).deliver
        format.html { redirect_to @login, notice: 'Login was successfully created.' }
        format.json { render action: 'show', status: :created, location: @login }
      else
        format.html { render action: 'new' }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logins/1
  # PATCH/PUT /logins/1.json
  def update
    respond_to do |format|
      if @login.update(login_params)
        format.html { redirect_to @login, notice: 'Login was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1
  # DELETE /logins/1.json
  def destroy
    @login.destroy
    respond_to do |format|
      format.html { redirect_to logins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login
      @login = Login.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_params
      params.require(:login).permit(:name, :userid, :dob, :cell, :gender, :address)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:login_id, :pname, :price, :qty)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/AboutUs.html.erb
<h1>Home#AboutUs</h1>
<p>Find me in app/views/home/AboutUs.html.erb</p>

app/views/home/ContactUs.html.erb
<h1>Home#ContactUs</h1>
<p>Find me in app/views/home/ContactUs.html.erb</p>

app/views/home/OverView.html.erb
<h1>Home#OverView</h1>
<p>Find me in app/views/home/OverView.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Raghava</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<body>
<div id="templatemo_container">
	<div id="templatemo_banner">
    	<div id="logo"></div>
        <!--  Free CSS Templates @ www.TemplateMo.com  -->
        <div id="search_section">
            <form action="#" method="get">
                <input type="text" value="Enter keyword here..." name="q" size="10" id="searchfield" title="searchfield" onfocus="clearText(this)" onblur="clearText(this)" />
              <input type="submit" name="Search" value="Search" alt="Search" id="searchbutton" title="Search" />
            </form>
        </div> 

    </div> <!-- end of banner -->
    
    <div id="templatemo_menu">

      <%= render :partial => 'membership/menu' %>
           
	  </div> <!-- end of menu -->

	<div id="templatemo_content_wrapper">
    	<div id="templatemo_content">
    
    	<div class="column_w210 fl">
        
          <div class="header_01">
              Latest Blog Posts
            </div>
            
      <div class="latest_news">
            <div class="header_03">[29-OCT-2024]</div>
            <div class="header_02"><a href="#">Aenean a bibendum augue</a></div>
                
                <p>Praesent eu ligula quis nibh ullamcorper tempor non ultrices lacus.</p>
      </div>
                        
            <div class="margin_bottom_10"></div>
            
            <div class="latest_news">
                <div class="header_03">[28-OCT-2024]</div>
            <div class="header_02"><a href="#">Nulla pharetra leo eget </a></div>
                <p>Vivamus condimentum justo id tortor rhoncus eu ornare sem malesuada. </p>
			</div>
                        
            <div class="margin_bottom_10"></div>
            
            <div class="latest_news">
                <div class="header_03">[27-OCT-2024]</div>
    		    <div class="header_02"><a href="#">Vivamus metus justo</a></div>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
			</div>
                        
            <div class="margin_bottom_10"></div>
            
            <div class="rc_btn_01"><a href="#">Read All</a></div>
            
        
        	<div class="cleaner"></div>
        </div> <!-- end of a column -->
        
        <div class="column_w430 fl vl_divider">
        	
            <%= image_tag("templatemo_image_01.jpg", :alt => "image") %>
            
            <div class="header_01">Welcome to our photo site!</div>
            
            <%= yield %>
        
        	<div class="cleaner"></div>        
        </div> <!-- end of a column -->
        
       <div class="column_w210 fl vl_divider">
        
        	<div class="header_01">
            	Categories
            </div>
            
	        <%= render :partial => 'membership/right' %> 
            
        
        	<div class="cleaner"></div>
        </div> <!-- end of a column -->
        
        <div class="margin_bottom_20 h_divider"></div>        
        <div class="margin_bottom_20"></div>
        
        <div class="column_w920">
        
          <%= render :partial => 'membership/bottomimages'  %>
        </div>
    
    	<div class="cleaner"></div>
	</div> <!-- end of wrapper 02 -->        
    </div> <!-- end of wrapper 01 -->
    
    <div id="templatemo_footer">
    
    <ul class="footer_list">
            <li><a href="#" class="current">Home</a></li>
            <li><a href="#">Gallery</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Forum</a></li>
            <li><a href="#">About Us</a></li>
            <li class="last"><a href="#">Contact Us</a></li>
        </ul> 
        
        <div class="margin_bottom_10"></div>
        
        Copyright © 2048 <a href="#">Company Name</a> | <a href="http://www.iwebsitetemplate.com" target="_parent">Website Templates</a> by <a href="http://www.templatemo.com" target="_parent">Free Templates</a>
        
        <div class="margin_bottom_10"></div>
        
        <a href="http://validator.w3.org/check?uri=referer"><img style="border:0;width:88px;height:31px" src="http://www.w3.org/Icons/valid-xhtml10" alt="Valid XHTML 1.0 Transitional" width="88" height="31" vspace="8" border="0" /></a>
                <a href="http://jigsaw.w3.org/css-validator/check/referer"><img style="border:0;width:88px;height:31px"  src="http://jigsaw.w3.org/css-validator/images/vcss-blue" alt="Valid CSS!" vspace="8" border="0" /></a>
                
   	</div> <!-- end of footer -->
</div> <!-- end of container -->
<!--  Free CSS Template is provided by www.TemplateMo.com  -->
<div align=center>This template  downloaded form <a href='http://all-free-download.com/free-website-templates/'>free website templates</a></div>

</body>
</html>

app/views/layouts/brain.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Raghava</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<div id="topPan">
	<a><%= image_tag("logo.gif", :width => "219", :height => "58", :border => "0", :alt => "Brain Tech", :title => "Brain Tech") %></a>
	
    <div id="topimagePan"><%= image_tag("blank.gif", :alt => "image") %></div> 
	<ul>
		<li class="home">home</li>
		<li><a href="#">about us</a></li>
		<li><a href="#">support</a></li>
		<li><a href="#">solutions</a></li>
		<li><a href="#">books</a></li>
		<li><a href="#">contact</a></li>
  </ul>
</div>

<div id="bodyPan">
  <div id="leftPan">
  	<%= yield %>
  </div>
  <div id="rightPan">
  	<form action="" method="post" class="form1">
		<h2>member login</h2>
		<label>Name:</label>
		<input name="" type="text" />
		<label>Passward:</label>
		<input name="" type="password" />
		<label class="label1">a resistered member?</label>
		<input name="GO" type="submit" class="botton" id="GO" value="GO" />
	</form>
	<h3>more links</h3>
	<ul>
		<li><a href="#">www.braintech.com</a></li>
		<li><a href="#">www.brainmod.com</a></li>
		<li><a href="#">www.braintech2.com</a></li>
		<li><a href="#">www.modedu.com</a></li>
		<li><a href="#">www.modtech3.com</a></li>
		<li><a href="#">www.university.com</a></li>
	</ul>
	<div id="rightform2Pan">
	<form action="" method="get" class="form2">
		<h2>search</h2>
		<label>www.</label>
		<input name="" type="text" />
		<select name="select">
		  <option>.com</option>
		  <option>.org</option>
	    </select>
		<input name="search" type="submit"  class="search" id="search" value="SEARCH"/>
	</form>
	</div>
  </div>
</div>
<div id="bodyBottomPan">
  <div id="BottomLeftPan">
  	<p>about our <span>university</span></p>
  </div>
  
  <div id="BottomMiddlePan">
  	<p>Sed eros tellus, blandit in, tempus a, imperdiet at, ante. Phasellugittiss pedeamet,. Mauris mauris nibh, euismod nec, sagittis imperdietgittise, nonummy at, dui. Integer semimp sapien, faucibus it amet, tristique eu, blandit sit amet, massa. Nam lacinia.Proin ut velit id maurisluctus urisr vestibulum. Aenean condimentum.Donec iaculis </p>
	<p class="more"><a href="#">more</a></p>
  </div>
</div>
<div id="footerPan">
	<ul>
		<li><a href="#">home </a>| </li>
		<li><a href="#">about us</a>| </li>
		<li><a href="#">support</a>| </li>
		<li><a href="#">solutions</a>| </li>
		<li><a href="#">books</a>| </li>
		<li><a href="#">contact</a></li>
		</ul>
		<p class="copyright">©braintech. all right reserved.</p>
		<div id="footerPanhtml"><a href="http://validator.w3.org/check?uri=referer" target="_blank">HTML</a></div>
    	<div id="footerPancss"><a href="http://jigsaw.w3.org/css-validator/check/referer" target="_blank">CSS</a></div>
		<ul class="templateworld">
  			<li>design by:</li>
			<li><a href="http://www.templateworld.com" target="_blank">Template World</a></li>
 	   </ul>
</div>
</body>
</html>

app/views/logins/_form.html.erb
<%= form_for(@login) do |f| %>
  <% if @login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
      <% @login.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :userid %><br>
    <%= f.text_field :userid %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.date_select :dob %>
  </div>
  <div class="field">
    <%= f.label :cell %><br>
    <%= f.text_field :cell %>
  </div>
  <div class="field">
    <%= f.radio_button 'gender','female' %>
    <%= f.label :female %><br>
    <%= f.radio_button 'gender','male' %>
    <%= f.label :male %> 
    </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/logins/edit.html.erb
<h1>Editing login</h1>

<%= render 'form' %>

<%= link_to 'Show', @login %> |
<%= link_to 'Back', logins_path %>

app/views/logins/index.html.erb
<h1>Listing logins</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Userid</th>
      <th>Dob</th>
      <th>Cell</th>
      <th>Gender</th>
      <th>Address</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @logins.each do |login| %>
      <tr>
        <td><%= login.name %></td>
        <td><%= login.userid %></td>
        <td><%= login.dob %></td>
        <td><%= login.cell %></td>
        <td><%= login.gender %></td>
        <td><%= login.address %></td>
        <td><%= link_to 'Show', login %></td>
        <td><%= link_to 'Edit', edit_login_path(login) %></td>
        <td><%= link_to 'Destroy', login, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Login', new_login_path %>

app/views/logins/new.html.erb
<h1>New login</h1>

<%= render 'form' %>

<%= link_to 'Back', logins_path %>

app/views/logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @login.name %>
</p>

<p>
  <strong>Userid:</strong>
  <%= @login.userid %>
</p>

<p>
  <strong>dob:</strong>
  <%= @login.dob %>
</p>

<p>
  <strong>Cell:</strong>
  <%= @login.cell %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @login.gender %>
</p>

<p>
  <strong>Address:</strong>
  <%= @login.address %>
</p>

<%= link_to 'Edit', edit_login_path(@login) %> |
<%= link_to 'Back', logins_path %>

app/views/membership/_bottomimages.html.erb
         <div class="column_w190 fl margin_right_40">
            	<a href="#"><%= image_tag("templatemo_image_02.jpg", :alt => "image") %></a>
              <p>Nam sit amet justo vel libero tincidunt dignissim. Cras magna velit, pellentesque mattis, faucibus vitae, feugiat vitae. <a href="#">Read more...</a></p>                
          </div>
            
          <div class="column_w190 fl margin_right_40">
            	<a href="#"><%= image_tag("templatemo_image_03.jpg", :alt => "image") %></a>
          <p>Pellentesque tortor metus, gravida ut aliquet non, iaculis nec nisi. Null am ornare, mauris vitae vehicula veh icula. <a href="#">Read more...</a></p>                
          </div>
            
          <div class="column_w190 fl margin_right_40">
            	<a href="#"><%= image_tag("templatemo_image_04.jpg", :alt => "image") %></a>
          <p>Proin consequat interdum mauris id auctor. In justo dolor, luctus sed tristique vel, porttitor eu enim. In molestie vehicula pretium  iaculis. <a href="#">Read more...</a></p>                
          </div>
            
          <div class="column_w190 fl">
            	<a href="#"><%= image_tag("templatemo_image_05.jpg", :alt => "image") %></a>
          <p>Suspendisse odio erat, mattis in hend rerit id, iaculis at metus. Aliquam ligula justo, gravida sed pretium eu. <a href="#">Read more...</a></p>                
          </div>
        
       	  <div class="margin_bottom_15"></div>

app/views/membership/_brainyeild.html.erb
<h3>latest <span>blogs</span></h3>
		<h4><span>1.</span>kavin johnes</h4>
		<p><span>Lorem ipsum dolor sit amet, consectetuer</span> adipiscing elit. Cras sit amet neque a mauris semper sagittis. Sed facilisis turpis in elit. Nunc purus augue, ornare sed, bibendum vie</p>
		
	    <div id="leftblockoneLinkPan">
			<ul>
				<li class="comments">comments</li>
				<li class="more"><a href="#">more</a></li>
			</ul>
		</div>
		<p class="border"><%= image_tag("blank.gif", :alt => "image") %></p>
		<h4><span>2.</span>henry richard</h4>
		<p><span>Lorem ipsum dolor sit amet, consectetuer</span> adipiscing elit. Cras sit amet neque a mauris semper sagittis. Sed facilisis turpis in elit. Nunc purus augue, ornare sed, bibendum vie</p>
		<div id="leftblockoneLinktwoPan">
			<ul>
				<li class="comments">comments</li>
				<li class="more"><a href="#">more</a></li>
			</ul>
</div>

app/views/membership/_menu.html.erb
<ul>
    <li><a href="/users/sign_in" class="current"><span></span>Home</a></li>
    <li><a href="#"><span></span>Gallery</a></li>
    <li><a href="#"><span></span>Blog</a></li>
    <li>
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>
    </li>            
    <li><a href="/products"><span></span>Products</a></li>
    <li><a href="/logins"><span></span>Register</a></li>
</ul>

app/views/membership/_right.html.erb
<ul class="category_list">
           		<li><a href="#">Lorem ipsum dolor</a></li>
                <li><a href="#">Aenean ac lobortis felis</a></li>
                <li><a href="#">Cras eros dolor</a></li>
                <li><a href="#">Vivamus orci velit</a></li>
                <li><a href="#">Proin ultrices eros</a></li>
                <li><a href="#">Aliquam ac nisl eget</a></li>
                <li><a href="#">Praesent vehicula tellus</a></li>
                <li><a href="#">Mauris egestas nunc</a></li>
                <li><a href="#">Ut semper porta magna</a></li>
                <li><a href="#">Donec ante risus</a></li>
                <li><a href="#">Nunc bibendum neque</a></li>
    		</ul>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login_id %><br>
    <%= f.text_field :login_id %>
  </div>
  <div class="field">
    <%= f.label :pname %><br>
    <%= f.text_field :pname %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :qty %><br>
    <%= f.text_field :qty %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Login</th>
      <th>Pname</th>
      <th>Price</th>
      <th>Qty</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.login_id %></td>
        <td><%= product.pname %></td>
        <td><%= product.price %></td>
        <td><%= product.qty %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @product.login_id %>
</p>

<p>
  <strong>Pname:</strong>
  <%= @product.pname %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Qty:</strong>
  <%= @product.qty %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>